### ISSUE TITLE
Filter return type 

### ISSUE THREAD

**Issue by jpasquers** [wooorm/bcp-47-match#3]
Hey, I noticed that the return type defined here:

https://github.com/wooorm/bcp-47-match/blob/94c31cb95f2ed22a37714bd978952de19a2a1d13/index.js#L24

Is a single string for the `filter` type methods, but the readme and code suggest the actual return type is an Array aka `Tags`. Is there a piece I'm missing here? I'm glad to make a PR if you think it should be changed

**Comment by wooorm** [comment]
Been a while that I looked into this code, but seems you’re right that it should be `Tags` indeed! PR welcome!
